export const bannerData = [
  {
    id: 1,
    title: "MEN'S SLIDES",
    subtitle: "Under ₹149",
    bgColor: "bg-[#fbeedb]",
    textColor: "text-[#4a2e1b]",
    badgeColor: "bg-[#4a2e1b] text-white",
    image: "https://via.placeholder.com/600x400?text=Men%27s+Slides",
    alt: "Men's Slides",
  },
  {
    id: 2,
    title: "vivo T3 Ultra 5G",
    subtitle: "Launch 12th Sep, 12 PM",
    description: "Segment's Slimmest 5500 mAh Phone*",
    bgColor: "bg-[#1a1f2c]",
    textColor: "text-white",
    badgeColor: "bg-blue-600 text-white",
    image: "https://via.placeholder.com/600x400?text=Smartphone",
    alt: "vivo T3 Ultra 5G",
  },
  {
    id: 3,
    title: "TOP APPLIANCES",
    subtitle: "Up to 75% Off",
    description: "Washing Machines, TVs & More",
    bgColor: "bg-[#0f172a]",
    textColor: "text-white",
    badgeColor: "bg-yellow-500 text-black",
    image: "https://via.placeholder.com/600x400?text=Appliances",
    alt: "Top Appliances",
  },
];
